rollback test

diff --git a/.github/workflows/cicd-pipeline.yml b/.github/workflows/cicd-pipeline.yml
--- a/.github/workflows/cicd-pipeline.yml
+++ b/.github/workflows/cicd-pipeline.yml
@@ -52,10 +52,10 @@ jobs:
       run: |
         kubectl apply -f kubernetes/opentelemetry-demo.yaml -n $NAMESPACE --validate=false
 
-    # - name: Rollback
-    #   run: |
-    #     if ! kubectl apply -f kubernetes/opentelemetry-demo.yaml -n $NAMESPACE; then
-    #       echo "Apply failed. Rolling back to previous ReplicaSet..."
-    #       kubectl rollout undo deployment/ad -n $NAMESPACE
-    #     fi
+    - name: Rollback
+      run: |
+        if ! kubectl apply -f kubernetes/opentelemetry-demo.yaml -n $NAMESPACE; then
+          echo "Apply failed. Rolling back to previous version."
+          kubectl rollout undo deployment/ad -n $NAMESPACE
+        fi
 
