building and creating

diff --git a/.github/workflows/cicd-pipeline.yml b/.github/workflows/cicd-pipeline.yml
--- a/.github/workflows/cicd-pipeline.yml
+++ b/.github/workflows/cicd-pipeline.yml
@@ -25,10 +25,6 @@ jobs:
         aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
         aws-region: ${{ env.REGION }}
 
-    # - name: Set up kubeconfig
-    #   run: |
-    #     aws eks update-kubeconfig --region $REGION --name $CLUSTER_NAME
-
     - name: Log in to Amazon ECR
       id: login-ecr
       uses: aws-actions/amazon-ecr-login@v2
@@ -48,18 +44,18 @@ jobs:
       run: |
         docker compose push
 
-    # - name: (Optional) Scan image with Trivy
-    # #   uses: aquasecurity/trivy-action@master
-    # #   with:
-    # #     image-ref: "${{ secrets.ECR_REGISTRY }}/${{ secrets.ECR_REPOSITORY }}:latest"
+    - name: Set up kubeconfig
+      run: |
+        aws eks update-kubeconfig --region $REGION --name $CLUSTER_NAME
         
-    # # - name: Deploy OpenTelemetry Demo
-    # #   run: |
-    # #     kubectl apply -f kubernetes/opentelemetry-demo.yaml -n $NAMESPACE --validate=false
+    - name: Deploy OpenTelemetry Demo
+      run: |
+        kubectl apply -f kubernetes/opentelemetry-demo.yaml -n $NAMESPACE --validate=false
 
-  rollback:
-    if: failure()
-    runs-on: ubuntu-latest
-    steps:
-      - name: Rollback
-        run: echo "Rollback triggered. Implement rollback logic here (e.g., use Helm or revert manifest)."
+    # - name: Rollback
+    #   run: |
+    #     if ! kubectl apply -f kubernetes/opentelemetry-demo.yaml -n $NAMESPACE; then
+    #       echo "Apply failed. Rolling back to previous ReplicaSet..."
+    #       kubectl rollout undo deployment/ad -n $NAMESPACE
+    #     fi
+
